count: 20               # Maximum number of posts in a feed
excerpts: false         # Use post excerpts in feeds
external_links: true    # Linkposts should direct visitors to the linked site
category_feeds: false   # Add a feed for categories
categories: []          # Only add feeds for these categories. (empty adds feeds for all categories)

titles:
  main:      site.name - Posts
  links:     site.name - Links-only
  articles:  site.name - Articles-only
  category:  site.name - Posts in category.name

permalinks: 
  main:     /feed/
  links:    /feed/links/
  articles: /feed/articles/
  category: /feed/categories/category.name/
